magic_skillz = {
    1 : 'Alchemy',
    2 : 'Animation',
    3 : 'Conjuror',
    4 : 'Disintegration', 
    5 : 'Elemental',
    6 : 'Healing',
    7 : 'Illusion',
    8 : 'Immortality',
    9 : 'Invisibility',
    10 : 'Invulnerability',
    11 : 'Necromancer',
    12 : 'Omnipresent',
    13 : 'Omniscient',
    14 : 'Poison',
    15 : 'Possession', 
    16 : 'Self-detonation',
    17 : 'Summoning',
    18 : 'Water breathing',
}